---

- name: 设置持仓成本
  set_fact:
    持仓成本: "{{ hostvars[inventory_hostname]['最新持有金额'] - hostvars[inventory_hostname]['最新持有收益'] }}"

- name: 设置持有净值
  set_fact:
    持有净值: "{{ result_json['Data_netWorthTrend'][-1]['y']|float * hostvars[inventory_hostname]['持有份额'] }}"

- name: 设置持有收益
  set_fact:
    持有收益: "{{ 持有净值|float - 持仓成本|float }}"

- name: 收益率
  debug:
    msg:
    - 基金名字 {{ result_json['fS_name'] }}
    - 持有净值 {{ 持有净值 }}
    - 持仓成本 {{ 持仓成本 }}
    - 持有收益 {{ 持有收益 }}
    - 近一年收益率 {{ result_json['syl_1n'] }}
    - 近6月收益率 {{ result_json['syl_6y'] }}
    - 近三月收益率 {{ result_json['syl_3y'] }}
    - 近一月收益率 {{ result_json['syl_1y'] }}
    - 最新单位净值 {{ result_json['Data_netWorthTrend'][-1]['y'] }}
    - 最新同类排名 {{ result_json['Data_rateInSimilarType'][-1]['y'] }}/{{ result_json['Data_rateInSimilarType'][-1]['sc'] }}