#!/usr/bin/env ansible-playbook
---

- name: 获取基本信息
  gather_facts: no
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: 获取基本信息
      include_role:
        name: 获取基本信息
      loop: "{{ groups['基金'] }}"
      vars:
        code: "{{ item }}"