#!/usr/bin/env ansible-playbook
---

- name: 获取基金基本信息
  gather_facts: no
  hosts: 基金
  connection: local
  roles:
    - role: 获取基金基本信息
    - role: 设置更多基金信息

- name: 分析
  gather_facts: no
  hosts: 基金
  connection: local
  tasks:
    - fail:
        msg: "{{ result_json['fS_name'] }} 持有涨幅已经超过10%"
      when: 持有收益|float / 持仓成本|float > 0.1

    - fail:
        msg: "{{ result_json['fS_name'] }} 持有涨幅已经超过20%"
      when: 持有收益|float / 持仓成本|float > 0.2

    - fail:
        msg: "{{ result_json['fS_name'] }} 持有涨幅已经超过30%"
      when: 持有收益|float / 持仓成本|float > 0.3

    - fail:
        msg: "{{ result_json['fS_name'] }} 持有涨幅不超过5%"
      when: 持有收益|float / 持仓成本|float < 0.05
